/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab5_DotProduct */

#ifndef _Included_lab5_DotProduct
#define _Included_lab5_DotProduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab5_DotProduct
 * Method:    multi01
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_lab5_DotProduct_multi01
        (JNIEnv * env, jobject thisObj, jdoubleArray arrayA, jdoubleArray arrayB);

/*
 * Class:     lab5_DotProduct
 * Method:    multi02
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_lab5_DotProduct_multi02
        (JNIEnv * env, jobject thisObj, jdoubleArray arrayA);

/*
 * Class:     lab5_DotProduct
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lab5_DotProduct_multi03
        (JNIEnv * env, jobject thisObj);

#ifdef __cplusplus
}
#endif
#endif
