
package lab08.gazetomat;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Gazetomat", targetNamespace = "http://gazetomat.lab08/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Gazetomat {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getId", targetNamespace = "http://gazetomat.lab08/", className = "lab08.gazetomat.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://gazetomat.lab08/", className = "lab08.gazetomat.GetIdResponse")
    @Action(input = "http://gazetomat.lab08/Gazetomat/getIdRequest", output = "http://gazetomat.lab08/Gazetomat/getIdResponse")
    public int getId();

    /**
     * 
     * @return
     *     returns java.util.List<lab08.gazetomat.Paper>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItems", targetNamespace = "http://gazetomat.lab08/", className = "lab08.gazetomat.GetItems")
    @ResponseWrapper(localName = "getItemsResponse", targetNamespace = "http://gazetomat.lab08/", className = "lab08.gazetomat.GetItemsResponse")
    @Action(input = "http://gazetomat.lab08/Gazetomat/getItemsRequest", output = "http://gazetomat.lab08/Gazetomat/getItemsResponse")
    public List<Paper> getItems();

}
