
package lab08.gazetomat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GazetomatImplService", targetNamespace = "http://gazetomat.lab08/", wsdlLocation = "http://localhost:8081/WS/Automat?wsdl")
public class GazetomatImplService
    extends Service
{

    private final static URL GAZETOMATIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GAZETOMATIMPLSERVICE_EXCEPTION;
    private final static QName GAZETOMATIMPLSERVICE_QNAME = new QName("http://gazetomat.lab08/", "GazetomatImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/WS/Automat?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GAZETOMATIMPLSERVICE_WSDL_LOCATION = url;
        GAZETOMATIMPLSERVICE_EXCEPTION = e;
    }

    public GazetomatImplService() {
        super(__getWsdlLocation(), GAZETOMATIMPLSERVICE_QNAME);
    }

    public GazetomatImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GAZETOMATIMPLSERVICE_QNAME, features);
    }

    public GazetomatImplService(URL wsdlLocation) {
        super(wsdlLocation, GAZETOMATIMPLSERVICE_QNAME);
    }

    public GazetomatImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GAZETOMATIMPLSERVICE_QNAME, features);
    }

    public GazetomatImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GazetomatImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Gazetomat
     */
    @WebEndpoint(name = "GazetomatImplPort")
    public Gazetomat getGazetomatImplPort() {
        return super.getPort(new QName("http://gazetomat.lab08/", "GazetomatImplPort"), Gazetomat.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Gazetomat
     */
    @WebEndpoint(name = "GazetomatImplPort")
    public Gazetomat getGazetomatImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gazetomat.lab08/", "GazetomatImplPort"), Gazetomat.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GAZETOMATIMPLSERVICE_EXCEPTION!= null) {
            throw GAZETOMATIMPLSERVICE_EXCEPTION;
        }
        return GAZETOMATIMPLSERVICE_WSDL_LOCATION;
    }

}
